name: reusable-interactive-test

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apt-test: 
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          sudo apt update && sudo apt install socat netcat fping hping3 namp

          
